# Generated by Django 4.1.7 on 2023-03-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=225)),
                ('status', models.CharField(choices=[('В очереди', 'В очереди'), ('На работе', 'На работе'), ('Завершено', 'Завершено'), ('Просрочено', 'Просрочено')], default='В очереди', max_length=15)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
